// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wyrgpucsuahofpfkbqlh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind5cmdwdWNzdWFob2ZwZmticWxoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1NDMxNTksImV4cCI6MjA3MzExOTE1OX0.PwbwKaX4vkE5ItZQdDlYO6H2iTKqcBloxUYKBCutNc4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});